name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore src/UnoKeyboard/UnoKeyboard.csproj

    - name: Build project with
      run: dotnet build src/UnoKeyboard/UnoKeyboard.csproj --configuration Release

    - name: List packaged files
      run: ls -la src/UnoKeyboard/Packages

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/UnoKeyboard/Packages/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
